### ISSUE TITLE
Add note for Newer MacOS users

### ISSUE THREAD

**Issue by katiegrace** [kelpup/woof-CE#37]
It would be helpful to note that this will only work for older Macs. I could not run this on my MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports). I needed to use a VirtualBox to make this work
<img width="797" alt="Screen Shot 2022-03-30 at 5 52 33 PM" src="https://user-images.githubusercontent.com/42680309/160937165-9b89dcb0-b626-4731-9512-2eb94a4f5374.png">
!

**Comment by bgoodwine** [comment]
Added on the website! Thank you :)

**Comment by bgoodwine** [comment]
Also guru point was already added- I checked
