### ISSUE TITLE
Dropdown Overflow

### ISSUE THREAD

**Issue by sarahcullinan** [kelpup/woof-CE#38]
The drop down menus on the initial page overflow off the top of the screen. It may be beneficial and more user-friendly if you are able to  prevent this from happening! I have attached a screenshot of this happening.
![IMG_6700](https://user-images.githubusercontent.com/97462830/160942194-401c1129-43f5-43be-85c0-62de0d921c2c.jpeg)

**Comment by bgoodwine** [comment]
Thanks! I put this under #22 - they're related. Guru point added! Thank you :)))
