### ISSUE TITLE
Might need task switching feature

### ISSUE THREAD

**Issue by Casardo-Chen** [kelpup/woof-CE#42]
Probably adding a task-switching bar is a good idea because it is now a little bit hard to switch from different software.
![IMG_5281](https://user-images.githubusercontent.com/88423904/161325528-17a0fbf7-6ed1-4081-bf92-4863747b0219.JPG)

**Comment by bgoodwine** [comment]
I think this one is outside of our capabilities at the moment :( but it's a good idea! i'm logging it on the discord so we can start working on it if we have time! thank you :) guru point added :)
