### ISSUE TITLE
Option Key when Booting

### ISSUE THREAD

**Issue by cmkuczun** [kelpup/woof-CE#45]
The instructions specify to press the Option key, but you have to hold it down to get an option to reboot with the new OS. Maybe modify the rebooting instructions to be more specific.

**Comment by cmkuczun** [comment]
![IMG-1562](https://user-images.githubusercontent.com/93489352/161333876-8e9444ae-d2be-4c9f-9525-0b1bab12e8c2.JPG)

**Comment by bgoodwine** [comment]
thanks claudia! moving [here](https://github.com/kelpup/kelpup.github.io/issues/24) to be added to website :) guru point added :))
