### ISSUE TITLE
Welcome Screen

### ISSUE THREAD

**Issue by bmatuch** [kelpup/woof-CE#46]
The welcome screen was a little bit confusing and I wasn't sure if I had correctly gotten onto Kelpup. Maybe try incorporating a message that says something like "Welcome!" and some easy startup steps so the user is more comfortable using the machine
<img width="862" alt="Screen Shot 2022-04-01 at 4 51 04 PM" src="https://user-images.githubusercontent.com/97462307/161339712-dee21129-862d-46a4-9623-a32f0d847f92.png">
.

**Comment by bgoodwine** [comment]
Thanks! We're working on that Adding to #22 - consolidating issues. Guru point added :)
