### ISSUE TITLE
Application Places Bar

### ISSUE THREAD

**Issue by sofialombardo** [kelpup/woof-CE#47]
I wasn't sure what the three pink boxes were, on the top left of the window next to "Application Places," at first. I think it would be useful to have the description feature when you hover over this part (The yellow boxes). For example, on my Mac it is called Desktops. The description feature was very useful for the other parts of your linux distribution when I wasn't sure what I was navigating over.
<img width="800" alt="Screen Shot 2022-04-01 at 5 03 43 PM" src="https://user-images.githubusercontent.com/97541761/161340963-aa435a66-80e5-41e8-a085-1a8e00490a7f.png">

**Comment by jeanfboueri** [comment]
Thanks Sofia!! We're gonna add a 'users' section to the website soon which is more about how to use Kelpup and explaining all the different things :) Guru point added by Bridget.
