### ISSUE TITLE
Have Terminal App on Home Screen

### ISSUE THREAD

**Issue by msilvest** [kelpup/woof-CE#48]
Since the terminal is what most users are using, I feel like it should be an app on the homescreen so that users can easily access it, probably right under browser.
<img width="1440" alt="Screen Shot 2022-04-01 at 5 18 02 PM" src="https://user-images.githubusercontent.com/93883585/161342812-0ea66548-2034-453d-8be8-8ebbd49af289.png">

**Comment by bgoodwine** [comment]
This is a really good idea! The menu set up on woof-CE is a little convoluted and we haven't been able to figure it out yet, but we're definitely going to try to replace the browser with the terminal. We're hoping people will use Kelpup to learn how to use terminal and how to dual-boot and such, then move on to other distros like Ubuntu or FossaPup if they liked Puppy. Moving to #55 - Guru point added :)
