### ISSUE TITLE
Bluetooth functionality

### ISSUE THREAD

**Issue by chanraybae** [kelpup/woof-CE#50]
Although I was glad to see Bluetooth pop up as an option on the taskbar, the detecting seemed a lot slower, and some devices further away did not work as well - whether that be due to Intel Bluetooth drivers not running properly - and a searching graphic, such as a blinking progress bar or refresh button would be a nice feature to prevent the user from thinking the program is just taking a longer time to find their device.
![20220402_065251](https://user-images.githubusercontent.com/90279463/161380630-d47fe071-f947-465b-955a-baa9569ab3fa.jpg)

**Comment by bgoodwine** [comment]
Thanks! Guru point added :) We'll look into it if we have time!

**Comment by bgoodwine** [comment]
(Issue closed because that's how we're keeping track of who's guru point is added- but we logged this in the discord :)
