### ISSUE TITLE
Issue Loading on a Microsoft Surface

### ISSUE THREAD

**Issue by awilgen2** [kelpup/woof-CE#51]
I went to systems programming office hours after receiving an error message when I tried to boot up with the USB. It was recommended to turn off my device encryption in my computer settings. I did this, but it still will not run on my computer. I am not sure if there is anything that you can do about this, but I have tried for a long time to google work arounds and am not finding anything. 

Here is what shows up when I try the new USB boot up. It shows the downloads on the USB for the system, but it says they are not able to be run when I select them...

![image](https://user-images.githubusercontent.com/97130454/161394238-eaccbb92-e63f-4d1e-9760-ab9413475d2a.png)

**Comment by bgoodwine** [comment]
Simon said the Surface has an issue and it's better to run Kelpup off VirtualBox because of this :( Issue moved to [here](https://github.com/kelpup/kelpup.github.io/issues/22) on the website. Thanks! Guru point added :)
