### ISSUE TITLE
Add Puppy Package Manager Tutorial

### ISSUE THREAD

**Issue by rwachte2** [kelpup/woof-CE#52]
Could it be possible to add a tutorial for Puppy Package Manager and on how to install new programs and files. Also, if there could be a message that shows that ppm is the package manager for this OS, as this was hard to figure out.

![kelpup](https://user-images.githubusercontent.com/97465631/161400190-4df9d313-311b-45c2-b528-5c93584ac3a8.png)

**Comment by jeanfboueri** [comment]
Thanks Ryan! We're definitely looking into adding a users section in the website that basically explains how to use the different features in Kelpup. Thanks for pointing this out!! Guru point added by @bgoodwine :)
