### ISSUE TITLE
Boot Troubleshoot

### ISSUE THREAD

**Issue by svntii** [kelpup/woof-CE#53]
https://drive.google.com/file/d/1p7IWsLmIC97K96elpShoxCXuCEn1x-eA/view?usp=sharing

Legion y540
I7
RTX2300
Windows 11

Unable to boot into Kelpup 

the link is a video of the bootup

Let me know if there is any issue accessing the clip

**Comment by bgoodwine** [comment]
Huh, that's weird... Maybe we need to re-add the 60 second pause back in. Closing this issue and opening that one. Guru point added :)

**Comment by svntii** [comment]
What do i do. I want to play around with the iso
