### ISSUE TITLE
Put 60 second pause back in :(

### ISSUE THREAD

**Issue by bgoodwine** [kelpup/woof-CE#54]

**Comment by jeanfboueri** [comment]
#53 - Because of this, gonna add back and we can ask him to test it again or see if it happens with anyone else

**Comment by bgoodwine** [comment]
Thanks to @[svntii](https://github.com/svntii)

**Comment by svntii** [comment]
Ill re-download and try again

**Comment by jeanfboueri** [comment]
@svntii i changed what might (?) be causing the issue you were having, the building will take around 30 minutes, and i'll give you that ISO so you can try, and let us know if it works :)

**Comment by bgoodwine** [comment]
looks like it didn't work :(
